name: sare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  dynamic_color: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/sare_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/sare_logo.png
  adaptive_icon_foreground: assets/images/sare_logo.png
  adaptive_icon_background: '#FFFFFF'
  web:
    generate: true
    image_path: assets/images/sare_logo.png
    background_color: '#FFFFFF'
    theme_color: '#C9352C'
  windows:
    generate: true
    image_path: assets/images/sare_logo.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/images/sare_logo.png
